In [ ]:
from google.colab import files
uploaded=files.upload()

Saving diabetes.csv to diabetes.csv


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


In [ ]:
# Load the dataset
df = pd.read_csv('diabetes.csv')

In [ ]:
# Check the first few rows and basic info
print(df.head())
print(df.info())
print(df.describe())

   Age  Gender   BMI  SBP  DBP   FPG  Chol   Tri   HDL   LDL   ALT   BUN  \
0   26       1  20.1  119   81  5.80  4.36  0.86  0.90  2.43  12.0  5.40   
1   40       1  17.7   97   54  4.60  3.70  1.02  1.50  2.04   9.2  3.70   
2   40       2  19.7   85   53  5.30  5.87  1.29  1.75  3.37  10.1  4.10   
3   43       1  23.1  111   71  4.50  4.05  0.74  1.27  2.60  36.5  4.38   
4   36       1  26.5  130   82  5.54  6.69  3.49  0.91  3.64  69.3  3.86   

    CCR  FFPG  smoking  drinking  family_histroy  Diabetes  
0  63.8  5.40      3.0       3.0               0         0  
1  70.3  4.10      1.0       1.0               0         0  
2  61.1  4.85      3.0       3.0               0         0  
3  73.4  5.30      2.0       3.0               0         0  
4  67.5  5.53      3.0       3.0               0         0  
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4303 entries, 0 to 4302
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          ----

In [ ]:
# Example of filling missing values
imputer = SimpleImputer(strategy='mean')
df_imputed = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)


In [ ]:
X = df_imputed.drop('BMI', axis=1)
y = df_imputed['BMI']


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [ ]:
clf = RandomForestClassifier(n_estimators=100, random_state=42)


In [ ]:
# Convert to integer type
y_train = y_train.astype(int)
y_test = y_test.astype(int)


In [ ]:
y = pd.Categorical(y).codes

In [ ]:
clf.fit(X_train, y_train)


RandomForestClassifier(random_state=42)

In [ ]:
# Make predictions
y_pred = clf.predict(X_test)

In [ ]:
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(class_report)

Accuracy: 0.12775842044134728
Confusion Matrix:
[[ 0  0  5  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  5  1  4  2  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  0  1  6  7  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  5  1 10  8 15  8  5  2  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  2 10  5  8  6 19  7  9  3  1  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  4  5  8 14 18 14 11  5  1  0  0  0  1  0  0  0  0  0  0]
 [ 0  0  1  4  7  9 19 19  6  7  6  2  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  5 12 24 20 15 12  9  3  3  0  0  0  0  0  0  0  0]
 [ 0  0  2  1  2 11  7 23 13 10 20 10  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  3 10 19 13 15 16  7  5  1  0  0  0  0  0  0  0]
 [ 0  0  0  2  2  2 11 15 17 13 12  3  4  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  3  4  7  8 14 11 13  4  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  5  5  8  4  9  1  2  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  1  4  2  3  3  6  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  2  5

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
